// ─────────────────────────────────────────────────────────────
// RunnerLens — Job Summary Builder
// ─────────────────────────────────────────────────────────────

import type { AggregatedReport } from './types';
import { REPORT_VERSION } from './constants';
import {
  renderStatCards,
  renderAreaChart,
  renderGanttChart,
  pickGanttColor,
  svgImg,
  type StatCard,
  type GanttStep,
} from './svg-charts';

function fmtDuration(sec: number): string {
  if (sec < 60) return `${Math.round(sec)}s`;
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return s > 0 ? `${m}m ${s}s` : `${m}m`;
}

function fmtMem(mb: number): string {
  return mb >= 1024 ? `${(mb / 1024).toFixed(1)} GB` : `${Math.round(mb)} MB`;
}

export function buildJobSummary(report: AggregatedReport): string {
  const parts: string[] = [];

  // ── Stat Cards ───────────────────────────────────────────
  const cards: StatCard[] = [
    {
      label: 'Runner',
      value: report.system.runner_os,
      sub: `${report.system.cpu_count} CPU · ${fmtMem(report.system.total_memory_mb)}`,
      color: '#3fb950',
    },
    {
      label: 'Duration',
      value: fmtDuration(report.duration_seconds),
      sub: `${report.sample_count} samples`,
      color: '#58a6ff',
    },
    {
      label: 'Avg CPU',
      value: `${report.cpu.avg.toFixed(1)}%`,
      sub: `peak ${report.cpu.max.toFixed(1)}%`,
      color: '#f0883e',
    },
    {
      label: 'Memory',
      value: fmtMem(report.memory.avg),
      sub: `of ${fmtMem(report.memory.total_mb)}`,
      color: '#bc8cff',
    },
  ];

  parts.push(svgImg(renderStatCards(cards), 'RunnerLens Stats'));

  // ── Area Charts (need >= 2 data points) ──────────────────
  const timeline = report.timeline;
  if (timeline && timeline.cpu_pct.length >= 2) {
    const stepSeps = report.steps?.map((s) => ({
      name: s.name,
      startedAt: s.started_at,
    }));

    // CPU chart
    parts.push(
      svgImg(
        renderAreaChart({
          title: 'CPU Usage',
          values: timeline.cpu_pct,
          color: '#58a6ff',
          yLabel: 'CPU %',
          startedAt: report.started_at,
          endedAt: report.ended_at,
          currentValue: `${report.cpu.latest.toFixed(1)}%`,
          steps: stepSeps,
          formatY: (v) => `${v.toFixed(0)}%`,
        }),
        'CPU Usage Chart',
      ),
    );

    // Memory chart
    parts.push(
      svgImg(
        renderAreaChart({
          title: 'Memory Usage',
          values: timeline.mem_mb,
          color: '#bc8cff',
          yLabel: 'Memory',
          startedAt: report.started_at,
          endedAt: report.ended_at,
          currentValue: fmtMem(report.memory.latest),
          steps: stepSeps,
          formatY: (v) => fmtMem(v),
        }),
        'Memory Usage Chart',
      ),
    );
  }

  // ── Gantt Timeline (need steps with timestamps) ──────────
  if (report.steps && report.steps.length > 0) {
    const ganttSteps: GanttStep[] = report.steps.map((s, i) => ({
      name: s.name,
      startedAt: s.started_at,
      completedAt: s.completed_at,
      durationSec: s.duration_seconds,
      color: pickGanttColor(i),
    }));

    parts.push(
      svgImg(
        renderGanttChart({
          steps: ganttSteps,
          totalStartedAt: report.started_at,
          totalEndedAt: report.ended_at,
        }),
        'Execution Timeline',
      ),
    );
  }

  // ── Footer ───────────────────────────────────────────────
  parts.push(
    `<p><sub>Generated by <a href="https://github.com/runnerlens/runner-lens">RunnerLens</a> v${REPORT_VERSION}</sub></p>`,
  );

  return parts.join('\n\n');
}
