// ─────────────────────────────────────────────────────────────
// RunnerLens — Job Summary Builder
//
// Renders dark-themed SVG charts → converts to PNG via
// @resvg/resvg-js → embeds as data:image/png;base64 <img> tags.
// ─────────────────────────────────────────────────────────────

import type { AggregatedReport } from './types';
import { REPORT_VERSION } from './constants';
import {
  renderStatCards,
  renderAreaChart,
  renderGanttChart,
  pickGanttColor,
  svgToPngDataUri,
  imgTag,
  fmtDuration,
  type GanttStep,
} from './svg-charts';

function fmtMem(mb: number): string {
  return mb >= 1024 ? `${(mb / 1024).toFixed(1)} GB` : `${Math.round(mb)} MB`;
}

// ── Public API ───────────────────────────────────────────────

export function buildJobSummary(report: AggregatedReport): string {
  const parts: string[] = [];

  // Stat cards
  const cardsSvg = renderStatCards([
    { label: 'Runner', value: report.system.runner_os, sub: `${report.system.cpu_count} CPU \u00b7 ${fmtMem(report.system.total_memory_mb)}`, color: '#3fb950' },
    { label: 'Duration', value: fmtDuration(report.duration_seconds), sub: `${report.sample_count} samples`, color: '#58a6ff' },
    { label: 'Avg CPU', value: `${report.cpu.avg.toFixed(1)}%`, sub: `peak ${report.cpu.max.toFixed(1)}%`, color: '#f0883e' },
    { label: 'Memory', value: fmtMem(report.memory.avg), sub: `of ${fmtMem(report.memory.total_mb)}`, color: '#bc8cff' },
  ]);
  const cards = svgToPngDataUri(cardsSvg);
  parts.push(imgTag(cards.uri, 'RunnerLens Stats', cards.width));

  // Area charts
  const timeline = report.timeline;
  if (timeline && timeline.cpu_pct.length >= 2) {
    const stepSeps = report.steps?.map((s) => ({
      name: s.name,
      startedAt: s.started_at,
    }));

    const cpuSvg = renderAreaChart({
      title: 'CPU Usage',
      values: timeline.cpu_pct,
      color: '#58a6ff',
      yLabel: 'CPU %',
      startedAt: report.started_at,
      endedAt: report.ended_at,
      currentValue: `${report.cpu.latest.toFixed(1)}%`,
      steps: stepSeps,
      formatY: (v) => `${v.toFixed(0)}%`,
    });
    const cpu = svgToPngDataUri(cpuSvg);
    parts.push(imgTag(cpu.uri, 'CPU Usage Chart', cpu.width));

    const memSvg = renderAreaChart({
      title: 'Memory Usage',
      values: timeline.mem_mb,
      color: '#bc8cff',
      yLabel: 'Memory',
      startedAt: report.started_at,
      endedAt: report.ended_at,
      currentValue: fmtMem(report.memory.latest),
      steps: stepSeps,
      formatY: (v) => fmtMem(v),
    });
    const mem = svgToPngDataUri(memSvg);
    parts.push(imgTag(mem.uri, 'Memory Usage Chart', mem.width));
  }

  // Gantt timeline
  if (report.steps && report.steps.length > 0) {
    const ganttSteps: GanttStep[] = report.steps.map((s, i) => ({
      name: s.name,
      startedAt: s.started_at,
      completedAt: s.completed_at,
      durationSec: s.duration_seconds,
      color: pickGanttColor(i),
    }));

    const ganttSvg = renderGanttChart({
      steps: ganttSteps,
      totalStartedAt: report.started_at,
      totalEndedAt: report.ended_at,
    });
    const gantt = svgToPngDataUri(ganttSvg);
    parts.push(imgTag(gantt.uri, 'Execution Timeline', gantt.width));
  }

  parts.push(
    `<sub>Generated by <a href="https://github.com/runnerlens/runner-lens">RunnerLens</a> v${REPORT_VERSION}</sub>`,
  );

  return parts.join('\n\n');
}
